import type { Metadata } from "next";
import "@/styles/main.scss";

export const metadata: Metadata = {
  title: "X. 무슨 일이 일어나고 있나요? / X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="react-root">{children}</div>
      </body>
    </html>
  );
}
